### ISSUE TITLE
Provide functionality for determining type of JSON object

### ISSUE THREAD

**Issue by tpecar-ltek** [FreeRTOS/coreJSON#117]
There are cases where one needs to invoke different parsers based on the type of JSON object, where the (root) object might be a single scalar.

`JSON_SearchT()` / `JSON_Iterate()` provide this when accessing elements _within_ an object, which is assumed to be a collection. I want to determine the type for the object itself.

Provide functionality to get the type of current JSON object (the function can assume that the content has already been validated via `JSON_Validate()`) as a `JSONTypes_t` enum.

**Comment by jasonpcarroll** [comment]
Hi @tpecar-ltek,
Thank you for reaching out. I will let the team know about your feature request.
Best,
Jason Carroll

**Comment by tanmoysen** [comment]
Hi @tpecar-ltek, unfortunately, this feature is not part of the FreeRTOS team's prioritized backlog at this point. If you are still blocked, please let us know by reopening the issue.
