### ISSUE TITLE
MISRA 13.5 Compliance

### ISSUE THREAD

**Issue by AndreyVV-100** [FreeRTOS/coreJSON#147]
Hi! Are this lines compliant MISRA C 2012 Rule 13.5? Functions ```skipSomething``` change ```start```. According to ```Appendix J``` in rules, this is persistent side effect ("Modifying an object") and functions shouldn't be used in right hand of ```||```.

https://github.com/FreeRTOS/coreJSON/blob/8d216b5876ba6953e8b60a20d32eae62992d09fe/source/core_json.c#L648
https://github.com/FreeRTOS/coreJSON/blob/8d216b5876ba6953e8b60a20d32eae62992d09fe/source/core_json.c#L854-L856
https://github.com/FreeRTOS/coreJSON/blob/8d216b5876ba6953e8b60a20d32eae62992d09fe/source/core_json.c#L1207-L1208

**Comment by ActoryOu** [comment]
Hi @AndreyVV-100,
I follow the steps in [coverity/README](https://github.com/FreeRTOS/coreJSON/tree/main/tools/coverity) to check if any MISRA violation exists in coreJSON. There is no violations in coreJSON and rule 13.5 is not deviated by [misra.config](https://github.com/FreeRTOS/coreJSON/blob/main/tools/coverity/misra.config). So I believe coreJSON is MISRA compliant.
Do you get any error/MISRA violations on this?

My result:
> ~/git/coreJSON/build/cov-out$ cov-format-errors --dir . --file "source" --exclude-files '(/build/|/test/)' --html-output html-out;
> Processing 0 errors.


Here is my environment:
> - Ubuntu 20.04 LTS
> - GCC 9.4
> - Coverity 2018.09

Thanks.

**Comment by AndreyVV-100** [comment]
@ActoryOu 
We are developing static code analyzer with support for checking compliance of MISRA C 2012 rules and we are using coreJSON for testing as one of the MISRA Compliant open-source projects.

The C language standard says that:
(a) evaluation of logical AND and OR operators proceeds left-to-right
(b) evaluation of a logical operator stops when the result can be determined.

So, in our case when for example evaluating
```(skipAnyLiteral(buf, start, max) == true) || (skipNumber(buf, start, max) == true)```
and if ```skipAnyLiteral``` is ```true```, ```skipNumber``` will not be evaluated. If evaluation of  ```skipNumber``` would result a side-effect, then that side-effect may or may not occur, depending on whether ```skipAnyLiteral``` evaluates to true or not.

In function ```skipNumber``` the value by the pointer start is changed : ```*start = i;``` — which we think is a persistent side-effect. The value by this pointer is further used in the ```skipArrayScalars``` function which may be contrary to programmer expectations.

Please tell me your opinion about this.

Thank you!

**Comment by ActoryOu** [comment]
Hi @AndreyVV-100,
Thanks for detail explaination!

Please allow us to have an internal discussion.
Will update you soon.

**Comment by archigup** [comment]
Pull request is here: https://github.com/FreeRTOS/coreJSON/pull/148

We'd be interested in hearing more about your checker; feel free to keep us updated!
