### ISSUE TITLE
MISRA C Compliance

### ISSUE THREAD

**Issue by AndreyVV-100** [FreeRTOS/coreJSON#152]
Hi! Сontinuing the issue #147 , our tool gave some new reports. Are this lines violation of rules?

1. Violation of Rule MISRA C 2012 10.3

https://github.com/FreeRTOS/coreJSON/blob/8c7ba865150f18472d9d1f145098ff47cd327ea6/source/core_json.c#L691

According to MISRA C 2012 standard paragraph 8.10 "The essential type model", in this example `value` is of Essentially Signed type category, and the constant `0U` is of Essentially Unsigned type category. Assigning the value to an object with different essential type category is prohibited by the rule 10.3.

2. Violation of Rule MISRA C 2012 20.12

https://github.com/FreeRTOS/coreJSON/blob/8c7ba865150f18472d9d1f145098ff47cd327ea6/source/core_json.c#L1039

In standard header file `assert.h` macro `assert` is defined as follows:

```c++
#  define assert(expr)              \
  ((void) sizeof ((expr) ? 1 : 0), __extension__ ({      \
      if (expr)                \
        ; /* empty */              \
      else                \
        __assert_fail (#expr, __FILE__, __LINE__, __ASSERT_FUNCTION);  \
    }))
# endif
```
So in this example macro parameter `isOpenBracket_` (which is also macro) is itself subject for further macro replacement `(#expr)`, supplied as `expr` parameter.

**Comment by manvensh** [comment]
Hi @AndreyVV-100 
Thanks a lot for your efforts. Let me discuss with the team about this and get back to you.

Regards,

**Comment by chinglee-iot** [comment]
We address this issue in PR #157. I use the coverity 2023.06.1 to check the MISRA deviations and this issue is not reported. It would be great if you can help to verify this patch in your environment. Thank you for reporting this issue.

**Comment by AndreyVV-100** [comment]
@chinglee-iot We checked this PR in our environment and there is no warning now.
