### ISSUE TITLE
JSON_Validate() return success on Illegal JSON

### ISSUE THREAD

**Issue by vasilchenkosv** [FreeRTOS/coreJSON#165]
JSON_Validate() skip wrong JSON document. In example result == JSONSuccess, but must be JSONIllegalDocument.

`const char* json = "{\"k1\":\"v1\",{\"k2\":\"v2\"}}";`
`JSONStatus_t result = JSON_Validate(json, strlen(json));`

**Comment by rawalexe** [comment]
Hello @vasilchenkosv,
Thank you for raising the bug, we will look into the problem and possible solutions internally, meanwhile if you have a quick solution to the problem we also accept PR from the community.

Thank you,

Best Regards,
AR

**Comment by AniruddhaKanhere** [comment]
@vasilchenkosv thank you for bringing this to our attention. As the PR https://github.com/FreeRTOS/coreJSON/pull/167 is merged, I shall be closing this issue.
Feel free to reopen this thread or open a new one if you feel that your issue has not been resolved. Thanks!
