### ISSUE TITLE
JSON_Validate() return JSONIllegalDocument on valid JSON

### ISSUE THREAD

**Issue by vasilchenkosv** [FreeRTOS/coreJSON#168]
JSON_Validate() return JSONIllegalDocument for valid JSON document.

```
const char* json = "{\"obj\":{}}";
JSONStatus_t result = JSON_Validate(json, strlen(json));
```

**Comment by moninom1** [comment]
Hi @vasilchenkosv 

Thank you for raising the bug, we will look into the problem and possible solutions internally, meanwhile if you have a quick solution for the issue, You can also create a PR for the contribution.

**Comment by moninom1** [comment]
Hi @vasilchenkosv , Closing the issue as the fix has been merged. Thank you
