### ISSUE TITLE
How to handle very large JSON files

### ISSUE THREAD

**Issue by GlenFlint** [FreeRTOS/coreJSON#85]
Could you please provide an example of how to handle large JSON files that may not fit into single string? Can the JSONPartial JSONStatus_t be used to continue parsing/validating with the next buffer?

**Comment by dan4thewin** [comment]
Hi, @GlenFlint .  I'm sorry to say that the parser is not intended for such a use case.  The JSONPartial status means that if more characters are added to the same buffer, then a subsequent JSON_Validate() on the same buffer could return JSONSuccess.  Contrast that with a JSONIllegalDocument result - no matter what is added to the buffer the result will always be the same.
